agent:
  name: "WriteSection Agent Enthusiastic English"
#  name_list: ["WriteSection", "WriteSection Agent Chinese", "WriteSection Agent English", "WriteSection Agent Formal Chinese", "WriteSection Agent Enthusiastic Chinese" , \
#  "WriteSection Agent Enthusiastic English", "WriteSection Agent Formal English"]

